directories:
  incoming: data
  storage: data
octopus:
  api_key: "from https://octopus.energy/dashboard/developer/"
  account: "A-XXXXXX"
  # optional:
  meter_serial: 12A3456789
  endpoint: "gas-meter-points"
myenergi:
  username: ""
  device_serial: ""
  api_key: "from https://support.myenergi.com/hc/en-gb/articles/5069627351185-How-do-I-get-an-API-key-"
tesla:
  email: ""
  installation_time_zone: "Europe/London"
