directories:
  incoming: data
  storage: data
octopus:
  api:
    mpan: 1234567891011
    meter_serial: 12A3456789
    api_key: "from https://octopus.energy/dashboard/developer/"
  charges:
    standing: 0.25
    cheap: 0.05
    normal: 0.138
