[tool.poetry]
name = "energy"
version = "0.1.0"
description = "Tools for exploring and reconciling energy usage data."
authors = ["Chris Withers <chris@withers.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22"
pandas = "^0.25.1"
watchdog = "^0.9.0"
configurator = {version = "^1.2",extras = ["yaml"]}
pendulum = "^2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
